import type { FastifyInstance } from 'fastify';
import { mount } from './bridge';
import { API_PREFIX } from '@/server/middleware/request-guard';
import * as c0 from '@/server/controllers/admin-access-codes';
import * as c1 from '@/server/controllers/admin-access-codes/_id';
import * as c2 from '@/server/controllers/admin-access-codes/_id/revoke';
import * as c3 from '@/server/controllers/admins';
import * as c4 from '@/server/controllers/admins/_id/credentials';
import * as c5 from '@/server/controllers/admins/_id/reset-password';
import * as c6 from '@/server/controllers/admins/_id/status';
import * as c7 from '@/server/controllers/admins/_id/temporary-password/reveal';
import * as c8 from '@/server/controllers/applications';
import * as c9 from '@/server/controllers/applications/_id/approve';
import * as c10 from '@/server/controllers/applications/_id/return';
import * as c11 from '@/server/controllers/assessments';
import * as c12 from '@/server/controllers/assessments/_id';
import * as c13 from '@/server/controllers/assessments/_id/check';
import * as c14 from '@/server/controllers/assessments/_id/key';
import * as c15 from '@/server/controllers/assessments/_id/scores';
import * as c16 from '@/server/controllers/assessments/_id/status';
import * as c17 from '@/server/controllers/attendance/sessions';
import * as c18 from '@/server/controllers/attendance/sessions/_id';
import * as c19 from '@/server/controllers/attendance/sessions/_id/close';
import * as c20 from '@/server/controllers/attendance/sessions/_id/mark';
import * as c21 from '@/server/controllers/attendance/sessions/_id/scan';
import * as c22 from '@/server/controllers/audit-logs/export';
import * as c23 from '@/server/controllers/auth/admin-access-code';
import * as c24 from '@/server/controllers/auth/admin-access-code/request';
import * as c25 from '@/server/controllers/auth/change-password';
import * as c26 from '@/server/controllers/auth/change-password/verify';
import * as c27 from '@/server/controllers/auth/forgot-password';
import * as c28 from '@/server/controllers/auth/google';
import * as c29 from '@/server/controllers/auth/google/callback';
import * as c30 from '@/server/controllers/auth/login';
import * as c31 from '@/server/controllers/auth/logout';
import * as c32 from '@/server/controllers/auth/reset-password';
import * as c33 from '@/server/controllers/auth/session';
import * as c34 from '@/server/controllers/auth/verify-email';
import * as c35 from '@/server/controllers/badges';
import * as c36 from '@/server/controllers/calendar';
import * as c37 from '@/server/controllers/calendar/_id';
import * as c38 from '@/server/controllers/classes';
import * as c39 from '@/server/controllers/classes/_id';
import * as c40 from '@/server/controllers/classes/_id/grades';
import * as c41 from '@/server/controllers/classes/_id/grades/export';
import * as c42 from '@/server/controllers/classes/_id/grades/status';
import * as c43 from '@/server/controllers/classes/_id/weights';
import * as c44 from '@/server/controllers/credentials/_id/reject';
import * as c45 from '@/server/controllers/credentials/_id/verify';
import * as c46 from '@/server/controllers/curricula/_id';
import * as c47 from '@/server/controllers/curricula/_id/subjects';
import * as c48 from '@/server/controllers/curricula/_id/subjects/_entryId';
import * as c49 from '@/server/controllers/documents';
import * as c50 from '@/server/controllers/documents/_id';
import * as c51 from '@/server/controllers/documents/_id/file';
import * as c52 from '@/server/controllers/documents/_id/review';
import * as c53 from '@/server/controllers/documents/_id/submit';
import * as c54 from '@/server/controllers/enrollments/_id/transition';
import * as c55 from '@/server/controllers/health';
import * as c56 from '@/server/controllers/instructor-profile';
import * as c57 from '@/server/controllers/learning-supports';
import * as c58 from '@/server/controllers/learning-supports/_id';
import * as c59 from '@/server/controllers/my/assessments/_id/start';
import * as c60 from '@/server/controllers/my/assessments/_id/submit';
import * as c61 from '@/server/controllers/notifications';
import * as c62 from '@/server/controllers/profile';
import * as c63 from '@/server/controllers/profile/password';
import * as c64 from '@/server/controllers/programs';
import * as c65 from '@/server/controllers/programs/_id';
import * as c66 from '@/server/controllers/programs/_id/curricula';
import * as c67 from '@/server/controllers/school-years';
import * as c68 from '@/server/controllers/school-years/_id/activate';
import * as c69 from '@/server/controllers/school-years/_id/archive';
import * as c70 from '@/server/controllers/school-years/_id/semester';
import * as c71 from '@/server/controllers/sections';
import * as c72 from '@/server/controllers/sections/_id';
import * as c73 from '@/server/controllers/sections/_id/students';
import * as c74 from '@/server/controllers/setup';
import * as c75 from '@/server/controllers/setup/status';
import * as c76 from '@/server/controllers/staff';
import * as c77 from '@/server/controllers/staff/_id';
import * as c78 from '@/server/controllers/staff/_id/reset-password';
import * as c79 from '@/server/controllers/staff/_id/status';
import * as c80 from '@/server/controllers/status-requests';
import * as c81 from '@/server/controllers/status-requests/_id/decide';
import * as c82 from '@/server/controllers/students';
import * as c83 from '@/server/controllers/students/_id';
import * as c84 from '@/server/controllers/students/_id/credentials';
import * as c85 from '@/server/controllers/students/_id/enrollments';
import * as c86 from '@/server/controllers/subjects';
import * as c87 from '@/server/controllers/subjects/_id';

/**
 * Every REST endpoint, as METHOD /api/v1/<path> -> controller.
 *
 * Path parameters are written :name; the controller file lives at the same
 * path under src/controllers with _name for the parameter.
 */
export function registerApiRoutes(app: FastifyInstance): void {
  mount(app, 'GET', `${API_PREFIX}/admin-access-codes`, c0.GET);
  mount(app, 'POST', `${API_PREFIX}/admin-access-codes`, c0.POST);
  mount(app, 'GET', `${API_PREFIX}/admin-access-codes/:id`, c1.GET);
  mount(app, 'POST', `${API_PREFIX}/admin-access-codes/:id/revoke`, c2.POST);
  mount(app, 'GET', `${API_PREFIX}/admins`, c3.GET);
  mount(app, 'POST', `${API_PREFIX}/admins`, c3.POST);
  mount(app, 'GET', `${API_PREFIX}/admins/:id/credentials`, c4.GET);
  mount(app, 'POST', `${API_PREFIX}/admins/:id/reset-password`, c5.POST);
  mount(app, 'POST', `${API_PREFIX}/admins/:id/status`, c6.POST);
  mount(app, 'POST', `${API_PREFIX}/admins/:id/temporary-password/reveal`, c7.POST);
  mount(app, 'GET', `${API_PREFIX}/applications`, c8.GET);
  mount(app, 'POST', `${API_PREFIX}/applications`, c8.POST);
  mount(app, 'POST', `${API_PREFIX}/applications/:id/approve`, c9.POST);
  mount(app, 'POST', `${API_PREFIX}/applications/:id/return`, c10.POST);
  mount(app, 'POST', `${API_PREFIX}/assessments`, c11.POST);
  mount(app, 'GET', `${API_PREFIX}/assessments/:id`, c12.GET);
  mount(app, 'PUT', `${API_PREFIX}/assessments/:id`, c12.PUT);
  mount(app, 'DELETE', `${API_PREFIX}/assessments/:id`, c12.DELETE);
  mount(app, 'POST', `${API_PREFIX}/assessments/:id/check`, c13.POST);
  mount(app, 'PUT', `${API_PREFIX}/assessments/:id/key`, c14.PUT);
  mount(app, 'PUT', `${API_PREFIX}/assessments/:id/scores`, c15.PUT);
  mount(app, 'POST', `${API_PREFIX}/assessments/:id/status`, c16.POST);
  mount(app, 'POST', `${API_PREFIX}/attendance/sessions`, c17.POST);
  mount(app, 'GET', `${API_PREFIX}/attendance/sessions/:id`, c18.GET);
  mount(app, 'POST', `${API_PREFIX}/attendance/sessions/:id/close`, c19.POST);
  mount(app, 'POST', `${API_PREFIX}/attendance/sessions/:id/mark`, c20.POST);
  mount(app, 'POST', `${API_PREFIX}/attendance/sessions/:id/scan`, c21.POST);
  mount(app, 'GET', `${API_PREFIX}/audit-logs/export`, c22.GET);
  mount(app, 'GET', `${API_PREFIX}/auth/admin-access-code`, c23.GET);
  mount(app, 'POST', `${API_PREFIX}/auth/admin-access-code`, c23.POST);
  mount(app, 'DELETE', `${API_PREFIX}/auth/admin-access-code`, c23.DELETE);
  mount(app, 'POST', `${API_PREFIX}/auth/admin-access-code/request`, c24.POST);
  mount(app, 'POST', `${API_PREFIX}/auth/change-password`, c25.POST);
  mount(app, 'POST', `${API_PREFIX}/auth/change-password/verify`, c26.POST);
  mount(app, 'POST', `${API_PREFIX}/auth/forgot-password`, c27.POST);
  mount(app, 'GET', `${API_PREFIX}/auth/google`, c28.GET);
  mount(app, 'GET', `${API_PREFIX}/auth/google/callback`, c29.GET);
  mount(app, 'POST', `${API_PREFIX}/auth/login`, c30.POST);
  mount(app, 'POST', `${API_PREFIX}/auth/logout`, c31.POST);
  mount(app, 'POST', `${API_PREFIX}/auth/reset-password`, c32.POST);
  mount(app, 'GET', `${API_PREFIX}/auth/session`, c33.GET);
  mount(app, 'POST', `${API_PREFIX}/auth/verify-email`, c34.POST);
  mount(app, 'POST', `${API_PREFIX}/badges`, c35.POST);
  mount(app, 'GET', `${API_PREFIX}/calendar`, c36.GET);
  mount(app, 'POST', `${API_PREFIX}/calendar`, c36.POST);
  mount(app, 'PUT', `${API_PREFIX}/calendar/:id`, c37.PUT);
  mount(app, 'DELETE', `${API_PREFIX}/calendar/:id`, c37.DELETE);
  mount(app, 'POST', `${API_PREFIX}/classes`, c38.POST);
  mount(app, 'PUT', `${API_PREFIX}/classes/:id`, c39.PUT);
  mount(app, 'DELETE', `${API_PREFIX}/classes/:id`, c39.DELETE);
  mount(app, 'GET', `${API_PREFIX}/classes/:id/grades`, c40.GET);
  mount(app, 'PUT', `${API_PREFIX}/classes/:id/grades`, c40.PUT);
  mount(app, 'GET', `${API_PREFIX}/classes/:id/grades/export`, c41.GET);
  mount(app, 'POST', `${API_PREFIX}/classes/:id/grades/status`, c42.POST);
  mount(app, 'PUT', `${API_PREFIX}/classes/:id/weights`, c43.PUT);
  mount(app, 'POST', `${API_PREFIX}/credentials/:id/reject`, c44.POST);
  mount(app, 'POST', `${API_PREFIX}/credentials/:id/verify`, c45.POST);
  mount(app, 'GET', `${API_PREFIX}/curricula/:id`, c46.GET);
  mount(app, 'PUT', `${API_PREFIX}/curricula/:id`, c46.PUT);
  mount(app, 'PATCH', `${API_PREFIX}/curricula/:id`, c46.PATCH);
  mount(app, 'GET', `${API_PREFIX}/curricula/:id/subjects`, c47.GET);
  mount(app, 'POST', `${API_PREFIX}/curricula/:id/subjects`, c47.POST);
  mount(app, 'DELETE', `${API_PREFIX}/curricula/:id/subjects/:entryId`, c48.DELETE);
  mount(app, 'POST', `${API_PREFIX}/documents`, c49.POST);
  mount(app, 'PUT', `${API_PREFIX}/documents/:id`, c50.PUT);
  mount(app, 'DELETE', `${API_PREFIX}/documents/:id`, c50.DELETE);
  mount(app, 'GET', `${API_PREFIX}/documents/:id/file`, c51.GET);
  mount(app, 'POST', `${API_PREFIX}/documents/:id/review`, c52.POST);
  mount(app, 'POST', `${API_PREFIX}/documents/:id/submit`, c53.POST);
  mount(app, 'POST', `${API_PREFIX}/enrollments/:id/transition`, c54.POST);
  mount(app, 'GET', `${API_PREFIX}/health`, c55.GET);
  mount(app, 'PUT', `${API_PREFIX}/instructor-profile`, c56.PUT);
  mount(app, 'POST', `${API_PREFIX}/learning-supports`, c57.POST);
  mount(app, 'PUT', `${API_PREFIX}/learning-supports/:id`, c58.PUT);
  mount(app, 'POST', `${API_PREFIX}/my/assessments/:id/start`, c59.POST);
  mount(app, 'POST', `${API_PREFIX}/my/assessments/:id/submit`, c60.POST);
  mount(app, 'GET', `${API_PREFIX}/notifications`, c61.GET);
  mount(app, 'POST', `${API_PREFIX}/notifications`, c61.POST);
  mount(app, 'PUT', `${API_PREFIX}/profile`, c62.PUT);
  mount(app, 'PUT', `${API_PREFIX}/profile/password`, c63.PUT);
  mount(app, 'GET', `${API_PREFIX}/programs`, c64.GET);
  mount(app, 'POST', `${API_PREFIX}/programs`, c64.POST);
  mount(app, 'GET', `${API_PREFIX}/programs/:id`, c65.GET);
  mount(app, 'PUT', `${API_PREFIX}/programs/:id`, c65.PUT);
  mount(app, 'PATCH', `${API_PREFIX}/programs/:id`, c65.PATCH);
  mount(app, 'GET', `${API_PREFIX}/programs/:id/curricula`, c66.GET);
  mount(app, 'POST', `${API_PREFIX}/programs/:id/curricula`, c66.POST);
  mount(app, 'GET', `${API_PREFIX}/school-years`, c67.GET);
  mount(app, 'POST', `${API_PREFIX}/school-years`, c67.POST);
  mount(app, 'POST', `${API_PREFIX}/school-years/:id/activate`, c68.POST);
  mount(app, 'GET', `${API_PREFIX}/school-years/:id/archive`, c69.GET);
  mount(app, 'POST', `${API_PREFIX}/school-years/:id/archive`, c69.POST);
  mount(app, 'POST', `${API_PREFIX}/school-years/:id/semester`, c70.POST);
  mount(app, 'POST', `${API_PREFIX}/sections`, c71.POST);
  mount(app, 'GET', `${API_PREFIX}/sections/:id`, c72.GET);
  mount(app, 'PUT', `${API_PREFIX}/sections/:id`, c72.PUT);
  mount(app, 'DELETE', `${API_PREFIX}/sections/:id`, c72.DELETE);
  mount(app, 'POST', `${API_PREFIX}/sections/:id/students`, c73.POST);
  mount(app, 'DELETE', `${API_PREFIX}/sections/:id/students`, c73.DELETE);
  mount(app, 'POST', `${API_PREFIX}/setup`, c74.POST);
  mount(app, 'GET', `${API_PREFIX}/setup/status`, c75.GET);
  mount(app, 'GET', `${API_PREFIX}/staff`, c76.GET);
  mount(app, 'POST', `${API_PREFIX}/staff`, c76.POST);
  mount(app, 'PUT', `${API_PREFIX}/staff/:id`, c77.PUT);
  mount(app, 'POST', `${API_PREFIX}/staff/:id/reset-password`, c78.POST);
  mount(app, 'POST', `${API_PREFIX}/staff/:id/status`, c79.POST);
  mount(app, 'POST', `${API_PREFIX}/status-requests`, c80.POST);
  mount(app, 'POST', `${API_PREFIX}/status-requests/:id/decide`, c81.POST);
  mount(app, 'GET', `${API_PREFIX}/students`, c82.GET);
  mount(app, 'POST', `${API_PREFIX}/students`, c82.POST);
  mount(app, 'GET', `${API_PREFIX}/students/:id`, c83.GET);
  mount(app, 'PUT', `${API_PREFIX}/students/:id`, c83.PUT);
  mount(app, 'GET', `${API_PREFIX}/students/:id/credentials`, c84.GET);
  mount(app, 'GET', `${API_PREFIX}/students/:id/enrollments`, c85.GET);
  mount(app, 'POST', `${API_PREFIX}/students/:id/enrollments`, c85.POST);
  mount(app, 'GET', `${API_PREFIX}/subjects`, c86.GET);
  mount(app, 'POST', `${API_PREFIX}/subjects`, c86.POST);
  mount(app, 'GET', `${API_PREFIX}/subjects/:id`, c87.GET);
  mount(app, 'PUT', `${API_PREFIX}/subjects/:id`, c87.PUT);
  mount(app, 'PATCH', `${API_PREFIX}/subjects/:id`, c87.PATCH);
}
